//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Outfit
    {   [DisplayName("Outfit")]
        public int OutfitID { get; set; }
        [DisplayName("Top")]
        public int TopID { get; set; }
        [DisplayName("Bottom")]
        public int BottomID { get; set; }
        [DisplayName("Shoes")]
        public int ShoeID { get; set; }
        [DisplayName("Accessories")]
        public int AccessoryID { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Bottom Bottom { get; set; }
        public virtual Sho Sho { get; set; }
        public virtual Top Top { get; set; }
    }
}
